### ISSUE TITLE
Range check error

### ISSUE THREAD

**Issue by limelect** [Projeto-ACBr-Oficial/FPDF-Pascal#1]
D10.2.3
demo 3
line 1440      l := l + cw[ord(c)];
range check error

**Comment by dopidaniel** [comment]
I can't reproduce the problem...

Can you please provide some Steps to reproduce it...

**Comment by limelect** [comment]
I fixed the problem
On line 1498 change to

      if ord(c)>255 then
       l := l + cw[255]
       else
      l := l + cw[ord(c)];

**Comment by dopidaniel** [comment]
But.. sice 'C' is a Char, it could never have a value greater then chr(255)...

Can you please provide some information to reproduce the problem ?

Please try these change, on 'var' declaration

  c: AnsiChar;

**Comment by dopidaniel** [comment]
Closed, no response..
