### ISSUE TITLE
PDFWeb / ContextString

### ISSUE THREAD

**Issue by Chandlr** [Projeto-ACBr-Oficial/FPDF-Pascal#16]
Could Context.ContextString be implemented ?
like this i mean:
https://github.com/stijnsanders/pdfweb/blob/master/Default.xxm

for example:
```
pdf := TFPDFExt.Create();
try
pdf.AddPage();
pdf.SetLineWidth(0.1);
pdf.SetFont('Arial', 'B', 14);
pdf.SetXY(10, 10);
pdf.Write(5,'Your internet address:'+pdf.ContextString(csRemoteAddress));
pdf.SaveToFile('.\hello.pdf');
finally
pdf.Free;
end;
```

Maybe i have misunderstood and have to write with `CreateContentStream` ?

**Comment by dopidaniel** [comment]
What is the final result on PDFWeb example ?

Please save the Stream to a file and attach it Herr

**Comment by Chandlr** [comment]
The example i thought of was Stijns PDFWeb example (link: http://213.118.132.142:2233/pdfweb/)
Which gives `csRemoteAddress` and `csUserAgent`

**Comment by dopidaniel** [comment]
On the example above "Context" Object, looks like a global Object for the used language

I don't think this should be inside FPDFPascal

Maybe you can use a Web/http framework, like https://github.com/HashLoad/horse
