### ISSUE TITLE
FPDF implementation by fpc: acompanha o fpcupdeluxe

### ISSUE THREAD

**Issue by josedachao** [Projeto-ACBr-Oficial/FPDF-Pascal#2]
FPDF implementation by pfc: acompanha o fpcupdeluxe (gero boletos e danfes, na nuvem e depois disponibilizamos via download do arquivo ou diretamente via e-mail do destinatário da loja, o comprador), também geramos relatórios e diversos outros arquivos em lotes. Roda redondinho em um container Docker.

comes with several examples common to the use of FPDF on console mode

Path: C:\fpcupdeluxe\fpcsrc\packages\fcl-pdf ==> (in my machine)

The fcl-pdf package contains a PDF GENERATING UNIT FPPDF THAT DOES NOT DEPEND
ON ANY EXTERNAL LIBRARIES.

The PDF generator has the following features:
- Support for basic shapes.
- Support for basic line styles.
- Dictionary support.
- Multi-page PDF.
- Image support.
- TTF Font support.
- Font embedding.
- Unicode font support.
- Stream Compression.
- Image embedding.
- Several paper types.
- Portrait/Landscape.
- Support for multiple units.
- Rotation matrix system.
- PDF creator information.
- Output validates by several PDF validators.

Todo:
- Implement TFPCustomCanvas descendent (TPDFCanvas) that draws on a PDF.
- Partial embedding of (unicode) fonts for smaller PDFs.
- On windows, allow to use native font mechanisms for extracting info from TTF files.

Optionally:
- PDF Forms.
- Archive format.
- Signature.
- File attachments.

**Comment by josedachao** [comment]
[test.pdf](https://github.com/Projeto-ACBr-Oficial/FPDF-Pascal/files/11186671/test.pdf)
arquivo gerado pelo programa console exemplo que acompanha a biblioteca, em caso de erro ao executar o programa, criar pasta fonts no mesmo diretório do programa e inserir no diretório as fontes faltantes, as imagens acompanham os arquivos do projeto. Executar o programa com o parâmetro adequado (h ou p), não me recordo ao certo, mas é só ler os fontes.

**Comment by dopidaniel** [comment]
A implementação da fcl-pdf é fantástica, mas não é compatível com Delphi ou FMX

**Comment by josedachao** [comment]
> A implementação da fcl-pdf é fantástica, mas não é compatível com Delphi ou FMX

Desculpe, Daniel, realmente, não me ative a questão da compatibilidade com o Delphi, nem lembrei ... por aqui usamos o Delphi só em código legado... de resto free pascal/lazarus.
Front-end Angular/TypeScript, mobile Flutter,  back em free pascal/lazarus e node.js. Como não imprimimos via dispositivo e não realizamos operações de automação comercial no mobile, acabamos por não usar o Delphi.

**Comment by dopidaniel** [comment]
Ficamos muito na dúvida em iniciar esse trabalho de migração da FPDF... consideramos projetos como o Mormot, FPDF, PowerPDF, e outros... 
No final iniciamos com a [implementação do Jean](https://github.com/jepafi/Free-JPDF-Pascal), mas acabamos reescrevendo quase tudo, para compatibilizar com a última versão do FPDF em PHP
