### ISSUE TITLE
可以支持webp格式生成pdf不？

### ISSUE THREAD

**Issue by R1209588** [Projeto-ACBr-Oficial/FPDF-Pascal#4]
RT:...目前大部分类似组件，都不能做到webp格式图片生成pdf..

**Comment by dopidaniel** [comment]
please use english

**Comment by R1209588** [comment]
Can it support webp format? Generate pdf in Webp format.

**Comment by R1209588** [comment]
eg ..https://github.com/riderkick/FMD/blob/04f9d021fedab3e2b5222aeca650301b3946881f/baseunits/Img2Pdf.pas#L4

**Comment by dopidaniel** [comment]
I didn't find any reference, how to insert WebP images, in a PDF.

You could convert them to PNG or JPG, and then add to the PDF
