### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by abpaula77** [Projeto-ACBr-Oficial/FPDF-Pascal#5]
Traduzir a documentação para portugues e converter os exemplos de codigo para Pascal Code.

**Comment by dopidaniel** [comment]
Olá @abpaula77 , podemos fechar esse caso ?

**Comment by abpaula77** [comment]
pode fechar. Faltam alguns arquivos ainda, mas eu sigo com eles e faço os pull request quando estiverem atualizados.
