### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by hohmannc85** [Projeto-ACBr-Oficial/FPDF-Pascal#7]
changing in fpdf.pas and compile it, it works with Mac as well.
maybe u add it in version 1.1

uses
  Classes,Contnrs,
  {$IfDef FPC}
   zstream
  {$Else}
   {$IfDef HAS_SYSTEM_GENERICS}
    System.Generics.Collections, System.Generics.Defaults,
   {$EndIf}
   ZLib
  {$EndIf},
    {$IFDEF MACOS}
  Macapi.Foundation,
  {$ENDIF}
  SysUtils;

function SwapBytes(Value: LongWord): LongWord;
type
  Bytes = packed array[0..3] of Byte;
begin
 {$IFDEF MSWINDOWS}
  Bytes(Result)[0] := Bytes(Value)[3];
  Bytes(Result)[1] := Bytes(Value)[2];
  Bytes(Result)[2] := Bytes(Value)[1];
  Bytes(Result)[3] := Bytes(Value)[0];
  {$ENDIF}

  {$IFDEF MACOS}
  Result := NSSwapInt(Value);
  {$ENDIF}
end;

**Comment by dopidaniel** [comment]
Please try an Update first...

See changes in: 
https://github.com/Projeto-ACBr-Oficial/FPDF-Pascal/compare/aa6844e008a4066da5b8351f969a8a42b41ce1f3...28a5d68f845dac9e9119f9bdf834afb49eb2345c

**Comment by hohmannc85** [comment]
does it work with macOS? because with my change is works in macos

**Comment by dopidaniel** [comment]
I don't have a MacOs to test it... 
But I prefer a simpler fix.. changing the Type to Cardinal, should work on all platforms
Please test the actual source code, if it does not work on MacOS, you can reopen these issue

**Comment by hohmannc85** [comment]
Oki thx
